@startuml

node "订单" {
[订单:订单主表]

[订单:订单主表]-->[订单:订单明细表]
}

node "库存情况" {
[订单:订单明细表]-->[库存情况:库存正常]

[订单:订单明细表]-->[库存情况:锁部分]

[订单:订单明细表]-->[库存情况:未锁缺货]
}

database '数据库' {
[库存情况:库存正常]-->wms_sale_stock_lock表

[库存情况:锁部分]-->wms_sale_stock_lock表
[库存情况:锁部分]-->pms_stock_out_report表

[库存情况:未锁缺货]-->pms_stock_out_report表

}

note right of [wms_sale_stock_lock表]
锁库记录,在锁库时进行锁定
end note

note right of [pms_stock_out_report表]
缺货数量统计,由pms定时任务刷新生成
end note


@enduml